version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Diallo972182
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s

  students:
    build: ./backend/students
    container_name: students-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/studentdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Diallo972182
    depends_on:
      database:
        condition: service_healthy

  professeur:
    build: ./backend/professeur
    container_name: professeurs-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/professeurdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Diallo972182
    depends_on:
      database:
        condition: service_healthy

  cours:
    build: ./backend/cours
    container_name: cours-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/coursedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Diallo972182
    depends_on:
      database:
        condition: service_healthy

  classes:
    build: ./backend/classes
    container_name: classes-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/classesdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Diallo972182
    depends_on:
      database:
        condition: service_healthy

  timetable:
    build: ./backend/timetable
    container_name: timetable-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/timetabledb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Diallo972182
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./Gestion2-main
    container_name: frontend-app
    ports:
      - "4200:80"
    depends_on:
      - students
      - professeurs
      - cours
      - classes
      - timetable

volumes:
  pgdata:
