  professeurs-service:
    build: ./backend/professeur
    container_name: professeurs-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/professeurdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Diallo972182
    depends_on:
      database:
        condition: service_healthy
