name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: 'abdullahdiallo'
  MAVEN_HOME: '/usr/share/maven'
  NODE_HOME: '/usr/local/bin'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Installer Java et Maven
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Maven
      run: sudo apt-get install maven -y

    # Installer Node.js et Angular CLI
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    # Build des services backend
    - name: Build Backend Services
      run: |
        SERVICES=("students" "professeur" "Cours" "Classes" "Timetable")
        for SERVICE in "${SERVICES[@]}"; do
          cd backend/$SERVICE
          mvn clean package
          cd -
        done

    # Charger les images Docker préconstruites
    - name: Load Prebuilt Docker Images
      run: |
        SERVICES=("students" "professeur" "Cours" "Classes" "Timetable")
        for SERVICE in "${SERVICES[@]}"; do
          docker load -i /path/to/local/${SERVICE}.tar
        done
        docker load -i /path/to/local/frontend.tar

    # Push des images Docker vers le registre
    - name: Push Docker Images
      run: |
        SERVICES=("students" "professeurs" "cours" "classes" "timetable")
        for SERVICE in "${SERVICES[@]}"; do
          docker tag $SERVICE $DOCKER_REGISTRY/${SERVICE}:latest
          docker push $DOCKER_REGISTRY/${SERVICE}:latest
        done
        docker tag frontend $DOCKER_REGISTRY/frontend:latest
        docker push $DOCKER_REGISTRY/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/